# General site settings
baseurl: ""
url: "http://FroggieStick.Github.io/"

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap

# Pagination settings
paginate: 8
paginate_path: "/page/:num"

# Library-specific pagination
paginate_library:
  enabled: true
  per_page: 8
  path: "/library/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
