#-------------------------------
# Site Settings
title: The Pond 
logo:  # You can add own logo. For example '/images/logo.png'.
description: SecOps and HTB Write Ups


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'
    - title: 'The Library'
      url: '/library/'


#-------------------------------
# Author Settings
author:
  name: FroggieSec
  avatar: '/images/logo.png'


#-------------------------------
# Hero Settings
hero:
  title: FroggieSec
  description: SecOps and CTF Writeups
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: FroggieSec@proton.me # Add your email for contact form
  description: Dont Email. Wont Answer lol. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:

- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/FroggieStick"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join